#
# code Climate and Coverage: https://codeclimate.com
#
languages:
  Ruby: false
  JavaScript: false
  PHP: true
  Python: false
exclude_paths:
  - app/i18n/*
  - app/public/*
  - app/emails/*
  - app/tests/*
