#
# code Climate and Coverage: https://codeclimate.com
#
languages:
  Ruby: false
  JavaScript: false
  PHP: true
  Python: false
exclude_paths:
  - data
  - public
  - src/i18n
  - src/migrations
  - src/views
  - tests
  - vendor
