#
# code Climate and Coverage: https://codeclimate.com
#
languages:
  Ruby: false
  JavaScript: false
  PHP: true
  Python: false
exclude_paths:
  - app/i18n
  - app/emails
  - app/tests
  - app/web/3rd
  - vendor

