<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Configuration' => '',
    'PHP info: ' => '',
    'dbname' => '',
    'email' => '',
    'enable email' => '',
    'host' => '',
    'login' => '',
    'password' => '',
    'permissions' => '',
    'system' => '',
    'PHP info' => '@@PHP інфо@@',
    'users' => '@@користувачі@@',
    'DB format' => 'БД формат',
    'book' => 'Книга',
    'cover max width, px' => 'макс. ширина обкладинки, px',
    'cover type' => 'тип обкладинки',
    'database' => 'база даних',
    'directory' => 'директорія',
    'file' => 'файл',
    'language' => 'мова',
    'library' => 'бібліотека',
    'name format' => 'формат назви',
    'no' => 'ні',
    'settings' => 'налаштування',
    'syncronization' => 'синхронізація',
    'theme' => 'тема',
    'time zone' => 'часовий пояс',
    'yes' => 'так',
];
