<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ISBN-13' => '',
    'Db' => '@@Бд@@',
    'Login' => '@@Вхід@@',
    'About' => 'Про',
    'About {version}' => 'Про {version}',
    'Added' => 'Додано',
    'All' => 'Всі',
    'Author' => 'Автор',
    'Books' => 'Книжки',
    'Compact' => 'Пакування',
    'Configuration' => 'Налаштування',
    'Extension' => 'Розширення',
    'Favorite' => 'Улюблене',
    'Library' => 'Бібліотека',
    'No' => 'Ні',
    'Publisher' => 'Видавець',
    'Read' => 'Прочитано',
    'Title' => 'Назва',
    'Year' => 'Рік',
    'Yes' => 'Так',
    'doing...' => 'виконую...',
];
