name: PHPUnit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      # see https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-a-matrix-for-your-jobs
      fail-fast: false
      matrix:
        php_version: ['8.4']
        db_type: ['sqlite', 'mysql']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          tools: composer
      - name: Set 'ghostscript'
        run: |
          sudo apt update
          sudo apt install ghostscript
      - name: Set PHP version
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php_version }}
      - name: Validate composer
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php_version }}-db-type${{ matrix.db_type }}
      - name: Install dependencies
        run: |
          composer install --no-progress
          composer show --no-dev
      - name: Run tests
        run: |
          XDEBUG_MODE=coverage ./vendor/bin/phpunit
          echo "TEST_RESULT_EXIT_CODE=$?" >> "$GITHUB_ENV"
